POST http://localhost:3000/event_create HTTP/1.1
content-type: application/json

{
    "eventName": "evenementTestRequete",
    "startDate": "1984-04-02 08:30:20",
    "endDate": "1984-04-02 08:30:20",
    "description": "description"
}

###

POST http://localhost:3000/createUser HTTP/1.1
content-type: application/json

{
    "firstName": "eeeeee",
    "lastName":  "Brunel",
    "passphrase":  "ab",
    "confirmPassphrase": "efkmwrefrme@fkef*!!",
    "email":  "newE3ewedm2effwefail@gmail.com",
    "school": "UQO",
    "birthday": "1984-04-02 08:30:20"
}




//GET https://example.com/comments/1 HTTP/1.1
