GET http://localhost:3000/home HTTP/1.1

###
POST http://localhost:3000/event_create HTTP/1.1
content-type: application/json

{
    "eventName": "evenementTestRequete",
    "startDate": "1984-04-02 08:30:20",
    "endDate": "1984-04-02 08:30:20",
    "description": "description"
}

###

POST http://localhost:3000/createUser HTTP/1.1
content-type: application/json

{
    "firstname": "test",
    "lastname":  "test",
    "passphrase":  "Password123*!",
    "confirmpassphrase": "Password123*!",
    "email":  "test@gmail.com",
    "school": "UQO",
    "birthday": "1984-04-02 08:30:20"
}


###
POST http://localhost:3000/login HTTP/1.1
Content-Type: application/json

{
    "email": "test@gmail.com",
    "passphrase": "Password123*!"
}

###
POST http://localhost:3000/logout HTTP/1.1

###

GET http://localhost:3000/faq HTTP/1.1
###
PUT http://localhost:3000/faq HTTP/1.1
Content-Type: application/json

{
    "question" : "Is this a test question 5 ?",
    "response" : "Yes it is !"
}

###

PATCH http://localhost:3000/faq HTTP/1.1
Content-Type: application/json

{
    "id":2,
    "question" : "Is this an update of question 2 ?",
    "response" : "Yes it is !"
} 

###
DELETE http://localhost:3000/faq HTTP/1.1
Content-Type: application/json

{
    "id":3
}
//GET https://example.com/comments/1 HTTP/1.1
