GET http://localhost:3000/home HTTP/1.1

###
POST http://localhost:3000/event_create HTTP/1.1
content-type: application/json

{
    "eventName": "evenementTestRequete",
    "startDate": "1984-04-02 08:30:20",
    "endDate": "1984-04-02 08:30:20",
    "description": "description"
}

###

POST http://localhost:3000/createUser HTTP/1.1
content-type: application/json

{
    "firstname": "AAA",
    "lastname":  "B2323",
    "passphrase":  "Password123*!",
    "confirmpassphrase": "Password123*!",
    "email":  "newEwe3dm211ef223fwewefail@gmail.com",
    "school": "UQO",
    "birthday": "1984-04-02 08:30:20"
}


###
POST http://localhost:3000/login HTTP/1.1
Content-Type: application/json

{
    "id": 1,
    "firstName": "Jean",
    "lastName": "Test222",
    "email": "Ricard@gmail.com"
}

###
POST http://localhost:3000/logout HTTP/1.1

//GET https://example.com/comments/1 HTTP/1.1
